### ISSUE TITLE
Dataset Download question

### ISSUE THREAD

**Issue by Asakurayoho** [CMU-MBL/CMU_PanopticDataset_2.0#1]
I follow the steps in readme, but there  is no download link in website: https://simtk.org/projects/cmupanopticdata.

**Comment by yohanshin** [comment]
Hi, the data is not visible if you are not logged in on SimTK. Once you log in, visit the project homepage and go to Data Share on Downloads tab. You can find the dataset there. Please let me know if there is any other issues.

**Comment by Asakurayoho** [comment]
Thank you for your answer. I can download the dataset now.
